//medicine constants
export const MEDICINE_REQUEST = 'MEDICINE_REQUEST'
export const  MEDICINE_SUCCESS = 'MEDICINE_SUCCESS'
export const MEDICINE_FAIL = 'MEDICINE_FAIL'
export const MEDICINE_RESET = 'MEDICINE_RESET'

//prescription constants
export const PRESCRIPTION_REQUEST = 'PRESCRIPTION_REQUEST'
export const PRESCRIPTION_SUCCESS = 'PRESCRIPTION_SUCCESS'
export const PRESCRIPTION_FAIL = 'PRESCRIPTION_FAIL'
export const PRESCRIPTION_RESET = 'PRESCRIPTION_RESET'

//dietchart constants
export const DIETCHART_REQUEST = 'DIETCHART_REQUEST'
export const DIETCHART_SUCCESS = 'DIETCHART_SUCCESS'
export const DIETCHART_FAIL = 'DIETCHART_FAIL'
export const DIETCHART_RESET = 'DIETCHART_RESET'